#!/bin/sh
#
# This hook was set by cargo-husky v1.5.0: https://github.com/rhysd/cargo-husky#readme

set -e

echo '+cargo test'
cargo test --all-features
echo '+cargo clippy'
cargo clippy
echo '+cargo format'
cargo fmt
